name = "locus-sync"
main = "src/index.js"
compatibility_date = "2026-04-01"
workers_dev = true

[[durable_objects.bindings]]
name = "LOCUS_ROOM"
class_name = "LocusRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "LocusRoom" ]

[vars]
ALLOWED_ORIGINS = "http://localhost:8020,http://127.0.0.1:8020,https://emh.github.io,https://emh.io"
